export const FETCH_DATA_REQUEST='FETCH_DATA_REQUEST';
export const FETCH_DATA_SUCCESS='FETCH_DATA_SUCCESS';
export const FETCH_DATA_FAILED='FETCH_DATA_FAILED';


export const ADD_COLOUMN="ADD_COLOUMN";
export const REMOVE_COLOUMN="REMOVE_COLOUMN";


export const FETCH_APP_REQUEST="FETCH_APP_REQUEST";
export const FETCH_APP_SUCCESS="FETCH_APP_SUCCESS";
export const FETCH_APP_FAILED="FETCH_APP_FAILED";